dist: trusty
language: rust
rust:
  - stable
  - beta
  - nightly

cache:
    - cargo
before_cache:
    - chmod -R a+r ${HOME}/.cargo

install: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ] && [ $TRAVIS_BRANCH = master ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

script: cargo test

notifications:
  email:
    on_success: never


after_success:
  - '[ $TRAVIS_RUST_VERSION = nightly ] &&
     [ $TRAVIS_BRANCH = master ] &&
     [ $TRAVIS_PULL_REQUEST = false ] &&
     cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID || true'
